package mix

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// Nested extract lists — source of truth for Go mixcache (client detect/lazy sets are in flatMixLayout.ts).

var ExtractFromRA2 = []string{
	"cache.mix", "load.mix", "local.mix", "neutral.mix",
	"conquer.mix", "generic.mix", "isogen.mix",
	"isotemp.mix", "temperat.mix", "tem.mix",
	"isosnow.mix", "snow.mix", "sno.mix",
	"isourb.mix", "urb.mix", "urban.mix",
	"sidec01.mix", "sidec02.mix",
}

var ExtractFromLanguage = []string{
	"audio.mix", "cameo.mix",
}

var ExtractFromAudio = []string{
	"audio.bag", "audio.idx",
}

var TopLevelCopy = []string{
	"language.mix", "multi.mix", "theme.mix",
}

type flatManifestFile struct {
	Name     string `json:"name"`
	Required bool   `json:"required"`
}

// BuildFlatManifestJSON returns the flat layout manifest for /mix-cache.
func BuildFlatManifestJSON() ([]byte, error) {
	files := []flatManifestFile{
		{Name: "language.mix", Required: true},
		{Name: "multi.mix", Required: true},
		{Name: "theme.mix", Required: false},
		{Name: "cache.mix", Required: true},
		{Name: "load.mix", Required: true},
		{Name: "local.mix", Required: true},
		{Name: "neutral.mix", Required: true},
		{Name: "audio.mix", Required: true},
		{Name: "conquer.mix", Required: true},
		{Name: "generic.mix", Required: true},
		{Name: "isogen.mix", Required: true},
		{Name: "cameo.mix", Required: true},
		{Name: "audio.bag", Required: true},
		{Name: "audio.idx", Required: true},
		{Name: "isotemp.mix", Required: false},
		{Name: "temperat.mix", Required: false},
		{Name: "tem.mix", Required: false},
		{Name: "isosnow.mix", Required: false},
		{Name: "snow.mix", Required: false},
		{Name: "sno.mix", Required: false},
		{Name: "isourb.mix", Required: false},
		{Name: "urb.mix", Required: false},
		{Name: "urban.mix", Required: false},
		{Name: "sidec01.mix", Required: true},
		{Name: "sidec02.mix", Required: true},
	}
	body := map[string]any{
		"format":  "flat",
		"version": 1,
		"files":   files,
		"note":    "Generated by Go mixcache from source mixes (ra2/language/multi/theme).",
	}
	return json.MarshalIndent(body, "", "  ")
}

type UnpackStats struct {
	Extracted int
	Missing   int
	Bytes     int64
}

// ExtractNamed writes listed entries from arch into outDir (skips missing).
func ExtractNamed(arch *Archive, names []string, outDir string, sourceLabel string, logf func(string, ...any)) (UnpackStats, error) {
	var st UnpackStats
	for _, name := range names {
		if !arch.Contains(name) {
			if logf != nil {
				logf("mix: missing in %s: %s", sourceLabel, name)
			}
			st.Missing++
			continue
		}
		data, err := arch.ReadFile(name)
		if err != nil {
			return st, fmt.Errorf("read %s from %s: %w", name, sourceLabel, err)
		}
		dst := filepath.Join(outDir, name)
		if err := os.WriteFile(dst, data, 0o644); err != nil {
			return st, err
		}
		st.Extracted++
		st.Bytes += int64(len(data))
		if logf != nil {
			logf("mix: wrote %s from %s (%.1fMiB)", name, sourceLabel, float64(len(data))/(1024*1024))
		}
	}
	return st, nil
}

// UnpackSources extracts nested packs from ra2.mix (+ language.mix) into outDir
// and writes flat manifest.json. Pure Go — no Bun/Node required.
func UnpackSources(sourceDir, outDir string, logf func(string, ...any)) error {
	if logf == nil {
		logf = func(string, ...any) {}
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	ra2Path := filepath.Join(sourceDir, "ra2.mix")
	ra2Data, err := os.ReadFile(ra2Path)
	if err != nil {
		return fmt.Errorf("read ra2.mix: %w", err)
	}
	ra2, err := Open(ra2Data)
	if err != nil {
		return fmt.Errorf("open ra2.mix: %w", err)
	}
	logf("mix: opened ra2.mix (%.1fMiB)", float64(len(ra2Data))/(1024*1024))
	if _, err := ExtractNamed(ra2, ExtractFromRA2, outDir, "ra2.mix", logf); err != nil {
		return err
	}

	langPath := filepath.Join(sourceDir, "language.mix")
	if langData, err := os.ReadFile(langPath); err == nil {
		lang, err := Open(langData)
		if err != nil {
			return fmt.Errorf("open language.mix: %w", err)
		}
		logf("mix: opened language.mix (%.1fMiB)", float64(len(langData))/(1024*1024))
		if _, err := ExtractNamed(lang, ExtractFromLanguage, outDir, "language.mix", logf); err != nil {
			return err
		}
	} else {
		logf("mix: language.mix not found, skipping nested audio/cameo extract")
	}

	audioPath := filepath.Join(outDir, "audio.mix")
	if audioData, err := os.ReadFile(audioPath); err == nil {
		audio, err := Open(audioData)
		if err != nil {
			return fmt.Errorf("open extracted audio.mix: %w", err)
		}
		if _, err := ExtractNamed(audio, ExtractFromAudio, outDir, "audio.mix", logf); err != nil {
			return err
		}
	}

	for _, name := range TopLevelCopy {
		src := filepath.Join(sourceDir, name)
		dst := filepath.Join(outDir, name)
		if src == dst {
			continue
		}
		data, err := os.ReadFile(src)
		if err != nil {
			continue
		}
		if err := os.WriteFile(dst, data, 0o644); err != nil {
			return err
		}
		logf("mix: copied %s (%.1fMiB)", name, float64(len(data))/(1024*1024))
	}

	man, err := BuildFlatManifestJSON()
	if err != nil {
		return err
	}
	man = append(man, '\n')
	if err := os.WriteFile(filepath.Join(outDir, "manifest.json"), man, 0o644); err != nil {
		return err
	}
	logf("mix: wrote manifest.json")
	return nil
}
